from fastapi import FastAPI, HTTPException, UploadFile, File
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from fastapi.responses import HTMLResponse, FileResponse
from pydantic import BaseModel
import requests
import os
import json
import time
import uuid
from typing import Optional
import aiofiles
import asyncio

app = FastAPI(title="AI Video Generator", description="Generate videos from text prompts using AI")

# Add CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Create directories for storing generated videos
os.makedirs("static/videos", exist_ok=True)
os.makedirs("static/images", exist_ok=True)

# Mount static files
app.mount("/static", StaticFiles(directory="static"), name="static")

class VideoRequest(BaseModel):
    prompt: str
    duration: Optional[int] = 3
    style: Optional[str] = "realistic"

class VideoResponse(BaseModel):
    video_url: str
    job_id: str
    status: str
    message: str

# Store job status in memory (in production, use Redis or database)
job_store = {}

@app.get("/", response_class=HTMLResponse)
async def read_root():
    """Serve the main HTML page"""
    with open("../frontend/index.html", "r") as f:
        return HTMLResponse(content=f.read())

@app.post("/api/generate-video", response_model=VideoResponse)
async def generate_video(request: VideoRequest):
    """Generate a video from text prompt"""
    job_id = str(uuid.uuid4())
    
    # Initialize job status
    job_store[job_id] = {
        "status": "processing",
        "progress": 0,
        "video_url": None,
        "message": "Starting video generation..."
    }
    
    try:
        # For demo purposes, we'll create a simple video generation simulation
        # In a real app, you would integrate with services like:
        # - Runway ML API
        # - Stable Video Diffusion
        # - Pika Labs API
        # - Text2Video models from Hugging Face
        
        # Simulate video generation process
        video_url = await simulate_video_generation(request.prompt, job_id)
        
        job_store[job_id].update({
            "status": "completed",
            "progress": 100,
            "video_url": video_url,
            "message": "Video generated successfully!"
        })
        
        return VideoResponse(
            video_url=video_url,
            job_id=job_id,
            status="completed",
            message="Video generated successfully!"
        )
        
    except Exception as e:
        job_store[job_id].update({
            "status": "failed",
            "progress": 0,
            "video_url": None,
            "message": f"Error: {str(e)}"
        })
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/api/job-status/{job_id}")
async def get_job_status(job_id: str):
    """Get the status of a video generation job"""
    if job_id not in job_store:
        raise HTTPException(status_code=404, detail="Job not found")
    
    return job_store[job_id]

async def simulate_video_generation(prompt: str, job_id: str):
    """
    Simulate video generation process.
    In a real implementation, replace this with actual AI video generation API calls.
    """
    
    # Update progress
    for progress in range(0, 101, 20):
        job_store[job_id]["progress"] = progress
        job_store[job_id]["message"] = f"Generating video... {progress}%"
        await asyncio.sleep(0.5)  # Simulate processing time
    
    # For demo, create a simple text-based "video" file
    video_filename = f"video_{job_id}.txt"
    video_path = f"static/videos/{video_filename}"
    
    # Create a demo video description file
    video_content = f"""
Video Generation Demo
====================
Prompt: {prompt}
Generated at: {time.strftime('%Y-%m-%d %H:%M:%S')}
Duration: 3 seconds
Style: Realistic

[This is a demo. In a real implementation, this would be an actual video file
generated by AI models like Runway ML, Stable Video Diffusion, or similar services.]
    """
    
    async with aiofiles.open(video_path, 'w') as f:
        await f.write(video_content)
    
    return f"/static/videos/{video_filename}"

# Alternative implementation with Hugging Face API (commented out)
"""
async def generate_video_with_huggingface(prompt: str, job_id: str):
    # Example integration with Hugging Face Inference API
    # You would need to set up your HF API key
    
    import requests
    import os
    
    API_URL = "https://api-inference.huggingface.co/models/damo-vilab/text-to-video-ms-1.7b"
    headers = {"Authorization": f"Bearer {os.getenv('HUGGINGFACE_API_KEY')}"}
    
    def query(payload):
        response = requests.post(API_URL, headers=headers, json=payload)
        return response.content
    
    output = query({
        "inputs": prompt,
    })
    
    # Save the video
    video_filename = f"video_{job_id}.mp4"
    video_path = f"static/videos/{video_filename}"
    
    with open(video_path, "wb") as f:
        f.write(output)
    
    return f"/static/videos/{video_filename}"
"""

if __name__ == "__main__":
    import uvicorn
    import asyncio
    uvicorn.run(app, host="0.0.0.0", port=8000)